### ISSUE TITLE
Dataset arrangement

### ISSUE THREAD

**Issue by akashdexati** [taki0112/MUNIT-Tensorflow#1]
Hi @taki0112 
Can you please explain the dataset arrangement.
**1).** The folders name TrainA - TrainB - TestA - TestB.  What type of images are we supposed to place.
**2).** How do we specify the style images. ?

**Comment by taki0112** [comment]
1) 
Let's take the example of translation from summer to winter.
`dataset_name`= `summer2winter`
You can put a summer photo in the TrainA folder and a winter photo in the TrainB. 
The test folder is the same.

2)
You can not do it when training.
However, after the training is over, you can use the `num_style` option when you test.

For example, if `num_style = 3`, there are `3 different outputs` for one input.

**Comment by akashdexati** [comment]
@taki0112 

Can you please tell if its possible to train this model to place artificial beards on faces. And that too with different style beards.
If possible What type of data will I be preparing in that case ?
Specifically for style what type of Image will be needed since will be focused only on beard area.

**Comment by taki0112** [comment]
you want to `no beards on faces` <-> `beards on faces` ? 

if so,
Place the beardless image on train A and the bearded image on train B.
