### ISSUE TITLE
Output images

### ISSUE THREAD

**Issue by aplusc98** [taki0112/MUNIT-Tensorflow#14]
I ran the code on the summer2winter dataset as well as a custom dataset the outputs being generated are always just completely black images.. I executed the code with the exact commands as specified in the repo. Generally The code was run about 100k iterations for 7 epochs but the same outputs were generated even with 1 epoch .

**Comment by taki0112** [comment]
Modify the weights as follows.
https://github.com/NVlabs/MUNIT/blob/master/configs/summer2winter_yosemite256_folder.yaml

For summer2winter, cycle consistency loss is required.

**Comment by aplusc98** [comment]
Even after updating the weights the out is same as follows:
![2007-05-02 01:07:01_style1](https://user-images.githubusercontent.com/35690826/55874445-06533980-5bb0-11e9-891e-4e98f21c1ca4.jpg)

**Comment by taki0112** [comment]
I found that incorrect weight initialization had such an effect.

I've modified the code, so try again.
I used the same wight initialization as the author code.
