### ISSUE TITLE
Bug when using grayscale images

### ISSUE THREAD

**Issue by stefanbo92** [taki0112/MUNIT-Tensorflow#2]
Hey,
I think there is a little bug when you want to work with grayscale images.
When setting `--img_ch=1` I got an error because of tensor shape mismatch. This is due to the generator always producing an output with channel=3
https://github.com/taki0112/MUNIT-Tensorflow/blob/b0816e83f703c85e47f9ff61ab12161c584606ed/MUNIT.py#L145

This could be solved by simply changing this line to:
`x = conv(x, channels=self.img_ch, kernel=7, stride=1, pad=3, pad_type='reflect', scope='G_logit')`

Anyway, great implementation and many thanks!

**Comment by taki0112** [comment]
thank you !
I fix it
