### ISSUE TITLE
how to visualize the training processing？

### ISSUE THREAD

**Issue by Arthurzhangsheng** [taki0112/MUNIT-Tensorflow#3]
I use tensorboard to see the training processing, but can't visualize  the changes of images. there's no IMAGE tag  in the navigation bar, only SCALARS and GRAPHS.
Anyone know how to visualize the image processing?
Thanks~

**Comment by taki0112** [comment]
training result images will be in `results` folder

**Comment by Arthurzhangsheng** [comment]
oh,I see.
however, they are in the `sample` folder

**Comment by taki0112** [comment]
oh sorry

`sample` = training result images
`result` = test or guide result images

thank you

**Comment by Arthurzhangsheng** [comment]
thank you again for the reply~

**Comment by sanjayanayak** [comment]
Hi, I am unable to visualize training process in tensorboard. Its showing PCA graph in tensorboard.
tensorboard ver: 1.12
command line: tensorboard --logdir=.

When I use inspect argument then it is showing "no event files found within directory"
command line: tensorboard --logdir=. --inspect

Would u help me how can I visualize???
