### ISSUE TITLE
problems about "guide" photo & img_size

### ISSUE THREAD

**Issue by XiangyuWu** [taki0112/MUNIT-Tensorflow#4]
Hi taki0112! Thanks for your work. And when implementing your project, there are two problems confusing me. 
One is that what is "guide" photo working for? Does it complete a single photo style transfer work? 
The other one is that how to produce a image with different width and height, I search for it in your source code and find the img_size has only one parameter like 256, and it is used in both G and D. And the samples produced in the training time are all 256*256 pixels. Will the output be with different width and height as the same as my test photo? Maybe I can try this by myself firstly, but I am still a bit of  confusing.
Thanks for solving my problems.

**Comment by taki0112** [comment]
1. guide
`guide` is what you can do after training is over.
So input is `image corresponding to content` and `image corresponding to style`
Look at the end of the readme for the resulting image.

2. img_size
If the problem is height and weight of training data, I have fixed the code. 
```
example)
python main.py --img_h 256 --img_w 512
```

**Comment by XiangyuWu** [comment]
Got that! Thanks again!
